recordToCreate: "guestbook-prueba-xpto.infralab.local"

follower:
  follower:
    image:
      repository: gcr.io/google_samples/gb-redis-follower
      tag: v2
    resources:
      requests:
        cpu: 100m
        memory: 50Mi
  ports:
  - port: 6379
    targetPort: 0
  replicas: 1
  type: ClusterIP
frontend:
  phpRedis:
    image:
      repository: gcr.io/google_samples/gb-frontend
      tag: v5
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
  ports:
  - port: 80
    targetPort: 0
  replicas: 1
  type: LoadBalancer
leader:
  leader:
    image:
      repository: docker.io/redis
      tag: 6.0.5
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
  ports:
  - port: 6379
    targetPort: 6379
  replicas: 1
  type: ClusterIP
