apiVersion: v1
kind: Service
metadata:
  name: {{ include "guestbook-chart.fullname" . }}-frontend
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.recordToCreate }}
    external-dns.alpha.kubernetes.io/provider: "aws"
    external-dns.alpha.kubernetes.io/ttl: "60"
  labels:
    app: guestbook
    tier: frontend
  {{- include "guestbook-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.type }}
  selector:
    app: guestbook
    tier: frontend
  {{- include "guestbook-chart.selectorLabels" . | nindent 4 }}
  ports:
    {{- .Values.frontend.ports | toYaml | nindent 2 -}}
