apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx2
  template:
    metadata:
      labels:
        app: nginx2
    spec:
      containers:
      - image: nginx
        name: nginx2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx2
  annotations:
    external-dns.alpha.kubernetes.io/hostname: nginx.infralab.local
spec:
  selector:
    app: nginx2
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
