apiVersion: v1
kind: Service
metadata:
  name: {{ include "guestbook-chart.fullname" . }}-follower
  labels:
    app: redis
    role: follower
    tier: backend
  {{- include "guestbook-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.follower.type }}
  selector:
    app: redis
    role: follower
    tier: backend
  {{- include "guestbook-chart.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.follower.ports | toYaml | nindent 2 -}}