apiVersion: v1
kind: Service
metadata:
  name: {{ include "guestbook-chart.fullname" . }}-leader
  labels:
    app: redis
    role: leader
    tier: backend
  {{- include "guestbook-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.leader.type }}
  selector:
    app: redis
    role: leader
    tier: backend
  {{- include "guestbook-chart.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.leader.ports | toYaml | nindent 2 -}}